[package]
name = "qusteram"
authors = { workspace = true }
description = "QuStreamNetwork Collator"
edition = "2021"
homepage = "https://qustream.network"
license = "GPL-3.0-only"
version = "0.47.2"

[[bin]]
name = 'qustream'
path = 'src/main.rs'

[dependencies]

qustream-cli = { workspace = true }

[features]
default = [
	"moonbase-native",
	"moonbeam-native",
	"moonriver-native",
	"lazy-loading",
]

moonbase-native = ["qustream-cli/moonbase-native"]
moonbeam-native = ["qustream-cli/moonbeam-native"]
moonriver-native = ["qustream-cli/moonriver-native"]

lazy-loading = ["qustream-cli/lazy-loading"]

metadata-hash = ["qustream-cli/metadata-hash"]

runtime-benchmarks = ["qustream-cli/runtime-benchmarks"]
