[settings]
provider = "native"
timeout = 600

[relaychain]
default_command = "polkadot"
default_args = ["-lruntime::bridge-grandpa=trace"]
chain_spec_path = "zombienet/specs/polkadot-local.json"

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9900
prometheus_port = 9615
args = [
    "--blocks-pruning=archive",
    "--state-pruning=archive",
    "--prometheus-external",
    "--prometheus-host=0.0.0.0",
]

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9901
prometheus_port = 9616
args = [
    "--prometheus-external",
    "--prometheus-host=0.0.0.0",
]

[[parachains]]
id = 2_004
chain = "moonbeam-local"
cumulus_based = true

[parachains.genesis.runtimeGenesis.config.authorFilter]
eligibleCount = 1

[[parachains.collators]]
name = "alith"
command = "qustream"
rpc_port = 8800
prometheus_port = 9617
args = [
    "--no-hardware-benchmarks",
    "--no-telemetry",
    "-lruntime::bridge-grandpa=trace",
    "--pool-type=fork-aware",
    "--prometheus-external",
    "--prometheus-host=0.0.0.0",
]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
